//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Mascaret;
namespace DM
{
	public class ConversationPlan : Plan
	{
		private List<ConversationOperation> operations{ get; set;}
		public List<ConversationOperation> Operations {
			get { return operations; } 
		}

		public ConversationPlan (string planGoal) :base(planGoal)
		{
			operations = new List<ConversationOperation> ();
		}
		public void addOperation(ConversationOperation op){
			operations.Add (op);
		}

		public override BehaviorExecution createBehaviorExecution(InstanceSpecification host, Dictionary<String, ValueSpecification> p, bool sync)
		{
			ConversationPlanExecution cpe = new ConversationPlanExecution (this, host, p);
			return cpe;
		}

	}
}

