//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Mascaret
{
	public class UtteranceMessage
	{
		public enum MessageType {connection, speech, action, knowledge};
		public UtteranceMessage ()
		{
		}
		private string sender;
		public string Sender{get{return sender;}  set{sender = value;}  }
		private string receiver;
		public string Receiver{get{return receiver;}  set{receiver = value;}  }
		private MessageType type;
		public MessageType Type{get{return type;}  set{type = value;}  }
		private string content;
		public string Content{get{return content;}  set{content = value;}  }
		private string utteranceSemanticForm;
		public string UtteranceSemanticForm{get{return utteranceSemanticForm;}  set{utteranceSemanticForm = value;}  }
		private object genericContent;
		public object GenericContent{get{return genericContent;}  set{genericContent = value;}  }

	}
}

